name: GitHub Pages

on:
  push:
<<<<<<< HEAD
    branches: [main]  # mainブランチへのプッシュ時のみ実行

permissions:
  contents: write  # デプロイに必要な権限を明示
=======
    branches: [main]

permissions:
  contents: write
>>>>>>> 4274ed2 (ワークフローファイルを更新)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
<<<<<<< HEAD
          fetch-depth: 0  # 全ての履歴を取得
=======
          fetch-depth: 0
>>>>>>> 4274ed2 (ワークフローファイルを更新)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
<<<<<<< HEAD
          hugo-version: '0.147.9'  # 安定版を明示的に指定
=======
          hugo-version: '0.147.9'
>>>>>>> 4274ed2 (ワークフローファイルを更新)
          extended: true

      - name: Cache Hugo modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/hugo
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Build
        run: hugo --minify --gc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
<<<<<<< HEAD
          keep_files: false  # 前回のビルドファイルを削除
=======
          keep_files: false
EOL
>>>>>>> 4274ed2 (ワークフローファイルを更新)
